name: keep-streamlit-awake

on:
  schedule:
    - cron: "0 */3 * * *"    # alle 3 Stunden
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: GET each app once (no auto redirect), accept 2xx/3xx as OK
        shell: bash
        run: |
          set -u  # kein set -e, damit Fehler den Job nicht killen
          UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15"

          URLS=(
            "https://solarspitzengesetz-rechner.streamlit.app"
            "https://evo-rechner.streamlit.app"
            "https://atnnschwellenrechnersimpel.streamlit.app"
            "https://pv-profil-generator.streamlit.app"
            "https://schwellenwert-rechner-atypische-netznutzung.streamlit.app"
            "https://temperatur-stunden.streamlit.app"
            "https://wandlermesser.streamlit.app"
          )

          for base in "${URLS[@]}"; do
            # 1) Erstes „echtes“ GET auf die Embed-Ansicht (vermeidet oft Redirect-Schleifen)
            url="${base}/?embed=true&keepalive=$(date +%s)"
            echo "GET $url"
            code=$(curl -sS -o /dev/null -w "%{http_code}" \
              --http1.1 \
              -A "$UA" \
              -H "Cache-Control: no-cache" \
              -H "Pragma: no-cache" \
              --max-time 25 \
              "$url" || echo "000")
            echo "Status: $code"

            # 2) Wenn 3xx, noch ein kurzer „touch“ auf die Basis-URL (ohne -L, kein Loop)
            if [[ "$code" =~ ^3[0-9][0-9]$ ]]; then
              sleep 5
              echo "Second touch ${base}/"
              code2=$(curl -sS -o /dev/null -w "%{http_code}" \
                --http1.1 \
                -A "$UA" \
                --max-time 20 \
                "${base}/" || echo "000")
              echo "Second status: $code2"
            fi

            echo "----"
          done
