name: keep-streamlit-awake-browser

on:
  schedule:
    - cron: "7 * * * *"     # stündlich, leicht versetzt
  workflow_dispatch:

jobs:
  wake:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Playwright
        run: |
          npm init -y
          npm install playwright@1
          npx playwright install --with-deps chromium

      - name: Create wake script
        run: |
          cat > wake.mjs << 'EOF'
          import { chromium } from "playwright";
          const urls = [
            "https://solarspitzengesetz-rechner.streamlit.app",
            "https://evo-rechner.streamlit.app",
            "https://atnnschwellenrechnersimpel.streamlit.app",
            "https://pv-profil-generator.streamlit.app",
            "https://schwellenwert-rechner-atypische-netznutzung.streamlit.app",
            "https://temperatur-stunden.streamlit.app",
            "https://wandlermesser.streamlit.app"
          ];

          const ua = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15";

          const timeoutMs = 30000;        // pro Seite
          const settleMs  = 6000;         // kurze Wartezeit nach Netz idle

          const run = async () => {
            const browser = await chromium.launch({
              headless: true,
              args: ["--no-sandbox","--disable-dev-shm-usage"]
            });
            const context = await browser.newContext({
              userAgent: ua,
              viewport: { width: 1366, height: 768 },
              javaScriptEnabled: true
            });

            for (const base of urls) {
              const url = `${base}/?embed=true&keepalive=${Date.now()}`;
              const page = await context.newPage();
              console.log(`Wake ${url}`);
              try {
                await page.goto(url, { waitUntil: "networkidle", timeout: timeoutMs });
                await page.waitForTimeout(settleMs);
                // kleiner zweiter Touch auf die Basis URL
                await page.goto(base + "/", { waitUntil: "domcontentloaded", timeout: timeoutMs });
                await page.waitForTimeout(1500);
                console.log(`OK ${base}`);
              } catch (e) {
                console.log(`WARN ${base}: ${e.message}`);
              } finally {
                await page.close();
              }
            }
            await context.close();
            await browser.close();
          };

          run();
          EOF

      - name: Run wake script
        run: node wake.mjs
